CuteNinja\HOT\UserBundle\Entity\User:
    type: entity
    table: "`character`"
    repositoryClass: CuteNinja\HOT\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY

    manyToOne:
        referrer:
            targetEntity: CuteNinja\HOT\UserBundle\Entity\User
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinsColumn:
                name: referrer_id
                referencedColumnName: id
                nullable: true