nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
    paths:
        '^/api':
            allow_origin: %nelmio_cors_allowed_origins%
            allow_headers: ['Authorization', 'X-Requested-With', 'Content-Type', 'Accept', 'Origin']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600