cute_ninja_hot_character:
    resource: "@CuteNinjaHOTCharacterBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

cute_ninja_hot_user:
    resource: "@CuteNinjaHOTUserBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api_login_check:
    path: /api/login_check
