CuteNinja\HOT\WorkoutBundle\Entity\AbstractWorkout:
    type: entity
    table: "`workout`"
    inheritanceType: SINGLE_TABLE
    repositoryClass: CuteNinja\HOT\WorkoutBundle\Repository\WorkoutRepository
    discriminatorColumn:
        name: type
        type: string
    discriminatorMap:
        hot: CuteNinja\HOT\WorkoutBundle\Entity\HotWorkout
        community: CuteNinja\HOT\WorkoutBundle\Entity\CommunityWorkout

    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY

    fields:
        name:
            type: string
            scale: 0
            length: 50
            unique: true
            nullable: false
            precision: 0
        difficulty:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0

    oneToMany:
        workoutSteps:
            targetEntity: CuteNinja\HOT\WorkoutBundle\Entity\AbstractWorkoutStep
            cascade: {  }
            fetch: LAZY
            mappedBy: workout
            orderBy: { 'position': 'ASC' }
            joinColumn:
                name: workout_id
                referencedColumnName: id
                nullable: false
            orphanRemoval: tru