CuteNinja\HOT\WorkoutBundle\Entity\WorkoutDistanceStep:
    type: entity
    fields:
        distance:
            column: distance
            type: integer
            nullable: false
            unique: false