CuteNinja\HOT\WorkoutBundle\Entity\Workout:
    type: entity
    table: "`workout`"
    repositoryClass: CuteNinja\HOT\WorkoutBundle\Repository\WorkoutRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY

    fields:
        name:
            type: string
            scale: 0
            length: 50
            unique: true
            nullable: false
            precision: 0
        difficulty:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0