CuteNinja\HOT\WorkoutBundle\Entity\WorkoutRestStep:
    type: entity
    fields:
        duration:
            column: duration
            type: integer
            nullable: false
            unique: false