CuteNinja\HOT\WorkoutBundle\Entity\Exercise:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [common]
        name:
            expose: true
            groups: [common]
        difficulty:
            expose: true
            groups: [common]
        equipments:
            exopose: true
            groups: [equipment]