CuteNinja\HOT\WorkoutBundle\Entity\HotWorkout:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [common]

        name:
            expose: true
            groups: [common]

        difficulty:
            expose: true
            groups: [common]

        workoutSteps:
            expose: true
            groups: [workout-details]