CuteNinja\HOT\WorkoutBundle\Entity\WorkoutRestStep:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [common]
        exercise:
            expose: true
            groups: [common]
        duration:
            expose: true
            groups: [common]
        position:
            expose: true
            groups: [common]
