CuteNinja\HOT\WorkoutBundle\Entity\WorkoutNorStep:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [common]
        exercise:
            expose: true
            groups: [common]
        numberOfRepetition:
            expose: true
            groups: [common]
        position:
            expose: true
            groups: [common]
