CuteNinja\HOT\WorkoutBundle\Entity\WorkoutDistanceStep:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [common]
        exercise:
            expose: true
            groups: [common]
        distance:
            expose: true
            groups: [common]
        position:
            expose: true
            groups: [common]
