CuteNinja\HOT\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
    properties:
        username:
            - NotBlank: ~
            - Type: string
            - Length:
                min: 2
                max: 30
        email:
            - NotBlank: ~
            - Email: ~
            - Type: string
            - Length:
                min: 5
                max: 200
        password:
            - NotBlank: ~
            - Type: string
            - Length:
                min: 5
        referrer:
            - Type: CuteNinja\HOT\UserBundle\Entity\User

